spring:
  datasource:
    url: ${SPRING__DATASOURCE__URL}
    username: ${SPRING__DATASOURCE__USERNAME}
    password: ${SPRING__DATASOURCE__PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  ai:
    vectorstore:
      mariadb:
        initialize-schema: true
        schema-validation: false
        schema-name: chwimeet
        table-name: vector_store
        dimensions: 1536
        distance-type: COSINE

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG